//! **Drop parity** — `NpcTemplate.calculateDrops` against a transcription of
//! it, driven through the same scripted roll stream.
//!
//! The drop algorithm is the one piece of reward maths that cannot be swept as
//! an expression: it is a loop with a budget, an eviction rule and an early
//! `break`, and what it produces is a *list*, not a number. So the harness is
//! the same idea as `formula_parity` one level up: [`java`] holds a
//! transcription written from `NpcTemplate.java`, both sides consume an
//! identical scripted sequence of rolls, and the item lists have to match. A
//! divergence in **roll order** fails it just as loudly as a divergence in the
//! arithmetic, which is what makes it a parity test rather than a re-statement
//! of the port.

use super::*;

use crate::data::npc_data::{DropGroup, DropHolder, NpcTemplate};
use std::cell::Cell;
use std::collections::HashMap;

/// The scripted roll stream. `World::roll` pops `forced_rolls`, and
/// `World::roll_f64` is `roll(1_000_000) / 1_000_000`, so one queue of `i32`
/// drives every draw both sides make — as long as they make them in the same
/// order, which is half of what this file checks.
struct Rolls {
    values: Vec<i32>,
    pos: Cell<usize>,
}

impl Rolls {
    /// A deterministic stream, generated by a small LCG so a failure can be
    /// reproduced from its seed alone.
    fn seeded(seed: u64, len: usize) -> Self {
        let mut state = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1);
        let mut values = Vec::with_capacity(len);
        for _ in 0..len {
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1_442_695_040_888_963_407);
            values.push(((state >> 33) % 1_000_000) as i32);
        }
        Self {
            values,
            pos: Cell::new(0),
        }
    }

    /// `Rnd.get(bound)`. **A forced roll ignores its bound** — `World::roll`
    /// returns the queued value verbatim, because the queue is a script rather
    /// than a random source. The transcription mirrors that so both sides
    /// consume the stream identically; the consequence is that the item
    /// *counts* in this grid are arbitrary, which is fine because they have to
    /// be arbitrary in the same way on both sides.
    fn next(&self, _bound: i32) -> i32 {
        let v = self.values[self.pos.get() % self.values.len()];
        self.pos.set(self.pos.get() + 1);
        v
    }

    /// `Rnd.nextDouble()`, as the port produces it.
    fn next_f64(&self) -> f64 {
        let v = self.values[self.pos.get() % self.values.len()];
        self.pos.set(self.pos.get() + 1);
        f64::from(v) / 1_000_000.0
    }
}

/// Everything the transcription reads out of `Config`.
#[derive(Clone)]
struct Cfg {
    occurrences_normal: i32,
    occurrences_raid: i32,
    death_chance: f64,
    death_amount: f64,
    by_id_chance: HashMap<i32, f64>,
    by_id_amount: HashMap<i32, f64>,
    adena_min_diff: i32,
    adena_max_diff: i32,
    adena_min_gap_chance: f64,
    item_min_diff: i32,
    item_max_diff: i32,
    item_min_gap_chance: f64,
}

/// This dist's `Rates.ini`, which is what makes the grid meaningful: one
/// occurrence, and a per-id chance override on adena that puts it **over
/// 100 %** and therefore outside the occurrence budget entirely.
fn dist_cfg() -> Cfg {
    Cfg {
        occurrences_normal: 1,
        occurrences_raid: 1,
        death_chance: 1.0,
        death_amount: 1.0,
        by_id_chance: HashMap::from([(57, 50.0), (6360, 50.0)]),
        by_id_amount: HashMap::from([(57, 30.0), (6360, 15.0)]),
        adena_min_diff: 8,
        adena_max_diff: 15,
        adena_min_gap_chance: 10.0,
        item_min_diff: 5,
        item_max_diff: 10,
        item_min_gap_chance: 10.0,
    }
}

mod java {
    use super::{Cfg, Rolls};
    use crate::data::npc_data::{DropHolder, NpcTemplate};

    const ADENA: i32 = 57;

    /// `Util.map`, which the port shares as `formulas::map_range`.
    fn map(value: f64, in_min: f64, in_max: f64, out_min: f64, out_max: f64) -> f64 {
        crate::model::formulas::map_range(value, in_min, in_max, out_min, out_max)
    }

    /// The chance chain of `calculateGroupDrop`/`calculateUngroupedDrop`. Herb
    /// and raid arms are folded away: both multipliers are 1 on this dist, and
    /// the grid carries no herb.
    fn rate_chance(cfg: &Cfg, item_id: i32) -> f64 {
        match cfg.by_id_chance.get(&item_id) {
            Some(&by_id) => by_id,
            None => cfg.death_chance,
        }
    }

    fn rate_amount(cfg: &Cfg, item_id: i32) -> f64 {
        match cfg.by_id_amount.get(&item_id) {
            Some(&by_id) => by_id,
            None => cfg.death_amount,
        }
    }

    /// `(long) (Rnd.get(min, max) * rateAmount)` — the port rounds and floors
    /// at 1 where Java truncates; every rate on this dist is an integer, so the
    /// two agree over this grid and the difference is recorded rather than
    /// swept.
    fn amount(rolls: &Rolls, drop: &DropHolder, rate: f64) -> i64 {
        let base = if drop.max > drop.min {
            drop.min + i64::from(rolls.next((drop.max - drop.min + 1) as i32))
        } else {
            drop.min
        };
        ((base as f64) * rate).round().max(1.0) as i64
    }

    /// ```java
    /// if ((dropOccurrenceCounter == 0) && (chance < 100) && (randomDrops != null) && (calculatedDrops != null))
    /// {
    ///     if ((rateChance == 1) && !randomDrops.isEmpty()) { cachedItem = randomDrops.remove(0); calculatedDrops.remove(cachedItem); }
    ///     dropOccurrenceCounter = 1;
    /// }
    /// ```
    struct Budget {
        counter: i32,
        calculated: Vec<(i32, i64)>,
        random: Vec<(i32, i64)>,
        cached: Option<(i32, i64)>,
    }

    impl Budget {
        fn new(counter: i32) -> Self {
            Self {
                counter,
                calculated: Vec::new(),
                random: Vec::new(),
                cached: None,
            }
        }

        fn make_room(&mut self, chance: f64, evict: bool) {
            if self.counter != 0
                || chance >= 100.0
                || self.random.is_empty()
                || self.calculated.is_empty()
            {
                return;
            }
            if evict {
                let cached = self.random.remove(0);
                if let Some(pos) = self.calculated.iter().position(|&i| i == cached) {
                    self.calculated.remove(pos);
                }
                self.cached = Some(cached);
            }
            self.counter = 1;
        }

        fn record(
            &mut self,
            cfg: &Cfg,
            item_id: i32,
            chance: f64,
            item: (i32, i64),
            evictable: bool,
        ) {
            let under_100 = match cfg.by_id_chance.get(&item_id) {
                Some(&by_id) => chance * by_id < 100.0,
                None => chance < 100.0,
            };
            if under_100 {
                self.counter -= 1;
                if evictable {
                    self.random.push(item);
                }
            }
            self.calculated.push(item);
        }

        fn finish(mut self) -> Vec<(i32, i64)> {
            if self.counter > 0
                && let Some(cached) = self.cached
            {
                self.calculated.push(cached);
            }
            self.calculated
        }
    }

    /// `calculateDrops(DropType.DROP, …)` — group pass then ungrouped pass,
    /// each with its own budget.
    pub fn calculate_drops(
        t: &NpcTemplate,
        killer_level: i32,
        cfg: &Cfg,
        rolls: &Rolls,
    ) -> Vec<(i32, i64)> {
        let mut out = Vec::new();
        if !t.drop_groups.is_empty() {
            out.extend(group_drops(t, killer_level, cfg, rolls));
        }
        if !t.drop_list_death.is_empty() {
            out.extend(ungrouped_drops(
                &t.drop_list_death,
                t,
                killer_level,
                cfg,
                rolls,
            ));
        }
        out
    }

    fn gaps(t: &NpcTemplate, killer_level: i32, cfg: &Cfg) -> (f64, f64) {
        let level_difference = f64::from(t.level - killer_level);
        (
            map(
                level_difference,
                -f64::from(cfg.adena_max_diff),
                -f64::from(cfg.adena_min_diff),
                cfg.adena_min_gap_chance,
                100.0,
            ),
            map(
                level_difference,
                -f64::from(cfg.item_max_diff),
                -f64::from(cfg.item_min_diff),
                cfg.item_min_gap_chance,
                100.0,
            ),
        )
    }

    /// ```java
    /// for (DropGroupHolder group : _dropGroups) {
    ///     totalChance = 0;
    ///     GROUP_DROP: for (DropHolder dropItem : group.getDropList()) {
    ///         …
    ///         if (rateChance == 1) totalChance += dropItem.getChance(); else totalChance = dropItem.getChance();
    ///         final double groupItemChance = totalChance * (group.getChance() / 100) * rateChance;
    ///         …
    ///         if ((Rnd.nextDouble() * 100) > levelGapChance) continue GROUP_DROP;
    ///         final ItemHolder drop = calculateGroupDrop(group, dropItem, victim, killer, groupItemChance);
    ///         if (drop == null) continue GROUP_DROP;
    ///         …
    ///         calculatedDrops.add(drop);
    ///         if (rateChance == 1) break;
    ///     }
    /// }
    /// ```
    fn group_drops(
        t: &NpcTemplate,
        killer_level: i32,
        cfg: &Cfg,
        rolls: &Rolls,
    ) -> Vec<(i32, i64)> {
        let (adena_gap, item_gap) = gaps(t, killer_level, cfg);
        let counter = if t.is_raid() {
            cfg.occurrences_raid
        } else {
            cfg.occurrences_normal
        };
        let mut budget = Budget::new(counter);
        if counter > 0 {
            for group in &t.drop_groups {
                let mut total_chance = 0.0;
                for drop in &group.items {
                    let rate = rate_chance(cfg, drop.item_id);
                    if rate == 1.0 {
                        total_chance += drop.chance;
                    } else {
                        total_chance = drop.chance;
                    }
                    let group_item_chance = total_chance * (group.chance / 100.0) * rate;
                    budget.make_room(group_item_chance, rate == 1.0);
                    let gap = if drop.item_id == ADENA {
                        adena_gap
                    } else {
                        item_gap
                    };
                    if rolls.next_f64() * 100.0 > gap {
                        continue;
                    }
                    if rolls.next_f64() * 100.0 >= group_item_chance {
                        continue;
                    }
                    let item = (
                        drop.item_id,
                        amount(rolls, drop, rate_amount(cfg, drop.item_id)),
                    );
                    budget.record(cfg, drop.item_id, group_item_chance, item, rate == 1.0);
                    if rate == 1.0 {
                        break;
                    }
                }
            }
        }
        budget.finish()
    }

    /// `calculateUngroupedDrops(DropType.DROP, …)`.
    fn ungrouped_drops(
        list: &[DropHolder],
        t: &NpcTemplate,
        killer_level: i32,
        cfg: &Cfg,
        rolls: &Rolls,
    ) -> Vec<(i32, i64)> {
        let (adena_gap, item_gap) = gaps(t, killer_level, cfg);
        let counter = if t.is_raid() {
            cfg.occurrences_raid
        } else {
            cfg.occurrences_normal
        };
        let mut budget = Budget::new(counter);
        if counter > 0 {
            for drop in list {
                budget.make_room(drop.chance, true);
                let gap = if drop.item_id == ADENA {
                    adena_gap
                } else {
                    item_gap
                };
                if rolls.next_f64() * 100.0 > gap {
                    continue;
                }
                let rate = rate_chance(cfg, drop.item_id);
                if rolls.next_f64() * 100.0 >= drop.chance * rate {
                    continue;
                }
                let item = (
                    drop.item_id,
                    amount(rolls, drop, rate_amount(cfg, drop.item_id)),
                );
                budget.record(cfg, drop.item_id, drop.chance, item, true);
            }
        }
        budget.finish()
    }
}

fn line(item_id: i32, min: i64, max: i64, chance: f64) -> DropHolder {
    DropHolder {
        item_id,
        min,
        max,
        chance,
    }
}

/// The templates under test, each aimed at one clause of the algorithm.
fn templates() -> Vec<(&'static str, NpcTemplate)> {
    let mut out = Vec::new();

    // A plain monster's list, in the dist's own shape: three rare items, adena
    // mid-list, then commons. Adena is the interesting line — its per-id
    // chance override (×50) puts it past 100 %, so Java never charges it to
    // the occurrence budget.
    let mut plain = crate::data::npc_data::default_template(90001);
    plain.level = 20;
    plain.drop_list_death = vec![
        line(116, 1, 1, 7.027),
        line(118, 1, 1, 5.579),
        line(112, 1, 1, 2.092),
        line(57, 13, 30, 70.0),
        line(17, 10, 30, 15.52),
        line(1868, 1, 1, 6.222),
        line(1867, 1, 1, 4.202),
    ];
    out.push(("plain monster", plain));

    // A 100 % line, which is outside the budget on both sides and must drop
    // whatever else happened.
    let mut guaranteed = crate::data::npc_data::default_template(90002);
    guaranteed.level = 20;
    guaranteed.drop_list_death = vec![
        line(1060, 1, 1, 100.0),
        line(116, 1, 1, 40.0),
        line(118, 1, 1, 40.0),
    ];
    out.push(("guaranteed line", guaranteed));

    // Grouped drops, the Stakato Nest shape: two groups, several lines each,
    // where Java accumulates the chances inside a group and breaks after the
    // first payout.
    let mut grouped = crate::data::npc_data::default_template(90003);
    grouped.level = 40;
    grouped.drop_groups = vec![
        DropGroup {
            chance: 70.0,
            items: vec![
                line(1342, 1, 1, 12.5),
                line(1343, 1, 1, 25.0),
                line(1344, 1, 2, 62.5),
            ],
        },
        DropGroup {
            chance: 30.0,
            items: vec![line(2000, 1, 1, 50.0), line(2001, 1, 1, 50.0)],
        },
    ];
    out.push(("grouped", grouped));

    // Both lists at once: Java runs two independent budgets over them.
    let mut mixed = crate::data::npc_data::default_template(90004);
    mixed.level = 40;
    mixed.drop_groups = vec![DropGroup {
        chance: 80.0,
        items: vec![line(1342, 1, 1, 30.0), line(1343, 1, 1, 70.0)],
    }];
    mixed.drop_list_death = vec![
        line(57, 100, 200, 80.0),
        line(116, 1, 1, 30.0),
        line(118, 1, 1, 30.0),
    ];
    out.push(("grouped + ungrouped", mixed));

    // A group carrying a per-id-rated line, which switches Java out of its
    // cumulative branch mid-group and stops it breaking.
    let mut rated_group = crate::data::npc_data::default_template(90005);
    rated_group.level = 40;
    rated_group.drop_groups = vec![DropGroup {
        chance: 100.0,
        items: vec![
            line(1342, 1, 1, 20.0),
            line(6360, 1, 1, 1.5),
            line(1343, 1, 1, 20.0),
        ],
    }];
    out.push(("group with a rated line", rated_group));

    out
}

fn drop_test_world() -> (World, i32) {
    let (mut world, _db_tx, _db_rx, _link_rx) = test_world();
    let cfg = dist_cfg();
    {
        let r = &mut world.cfg.rates;
        r.drop_max_occurrences_normal = cfg.occurrences_normal;
        r.drop_max_occurrences_raidboss = cfg.occurrences_raid;
        r.death_drop_chance_multiplier = cfg.death_chance;
        r.death_drop_amount_multiplier = cfg.death_amount;
        r.drop_chance_by_id = cfg.by_id_chance.clone();
        r.drop_amount_by_id = cfg.by_id_amount.clone();
        r.drop_adena_min_level_difference = cfg.adena_min_diff;
        r.drop_adena_max_level_difference = cfg.adena_max_diff;
        r.drop_adena_min_level_gap_chance = cfg.adena_min_gap_chance;
        r.drop_item_min_level_difference = cfg.item_min_diff;
        r.drop_item_max_level_difference = cfg.item_max_diff;
        r.drop_item_min_level_gap_chance = cfg.item_min_gap_chance;
    }
    world.cfg.premium.enabled = false;
    let killer = 3001;
    let chr = dummy_char(killer, "Killer");
    Player::from_char(&world.data, &chr).spawn_into(&mut world);
    (world, killer)
}

/// **The drop sweep.** Every template against every killer level, over 40
/// scripted roll streams each.
#[test]
fn drop_lists_match_java_across_the_grid() {
    let cfg = dist_cfg();
    let (mut world, killer) = drop_test_world();
    let mut cases = 0usize;
    let mut non_empty = 0usize;
    for (name, t) in templates() {
        for killer_level in [1, 18, 20, 22, 30, 45, 60] {
            for seed in 0..40u64 {
                world
                    .objects
                    .get_component_mut::<Player>(&killer)
                    .expect("killer")
                    .level = killer_level;

                let script = Rolls::seeded(seed, 64);
                world.forced_rolls.borrow_mut().clear();
                world
                    .forced_rolls
                    .borrow_mut()
                    .extend(script.values.iter().copied().cycle().take(512));
                let ours = crate::game_loop::death::roll_drops_for_test(&mut world, &t, killer);

                let script = Rolls::seeded(seed, 64);
                let theirs = java::calculate_drops(&t, killer_level, &cfg, &script);

                assert_eq!(
                    ours, theirs,
                    "{name} diverged — killer level {killer_level}, seed {seed}"
                );
                cases += 1;
                non_empty += usize::from(!ours.is_empty());
            }
        }
    }
    assert!(cases > 1_000, "the grid collapsed to {cases} cases");
    assert!(
        non_empty * 4 > cases,
        "only {non_empty}/{cases} rolls dropped anything — the grid is not exercising the algorithm"
    );
}

/// The clause the sweep was opened for, on its own: **adena never spends the
/// occurrence budget**, because its per-id chance override (×50) puts the
/// line's computed chance past 100 %.
///
/// The port used to test the *raw* line chance (70 % < 100) and charge adena to
/// the budget, which on this dist — one occurrence — meant that once any item
/// line ahead of it had paid out, adena was skipped entirely, and when adena
/// came first it blocked everything after it.
#[test]
fn adena_does_not_spend_the_occurrence_budget() {
    let (mut world, killer) = drop_test_world();
    world
        .objects
        .get_component_mut::<Player>(&killer)
        .expect("killer")
        .level = 20;
    let mut t = crate::data::npc_data::default_template(90010);
    t.level = 20;
    t.drop_list_death = vec![
        line(116, 1, 1, 100.0),
        line(57, 13, 30, 70.0),
        line(118, 1, 1, 100.0),
    ];
    // Every gap and chance roll succeeds; the count rolls land on the minimum.
    world.forced_rolls.borrow_mut().clear();
    world.forced_rolls.borrow_mut().extend([0; 64]);
    let drops = crate::game_loop::death::roll_drops_for_test(&mut world, &t, killer);
    let ids: Vec<i32> = drops.iter().map(|&(id, _)| id).collect();
    assert_eq!(
        ids,
        vec![116, 57, 118],
        "the 100 % lines and the adena line all drop"
    );
    assert_eq!(
        drops[1].1,
        13 * 30,
        "adena's per-id amount override (×30) applies to the rolled count"
    );
}
