//! Java `AbnormalVisualEffect` and `AbnormalType` — the client-side *look* and
//! the stacking key of an abnormal, as lookup tables generated from the Java
//! enums. The mechanics live in [`super::effect_flag`] and the effect handlers.

/// Java `AbnormalVisualEffect` — the client-side *look* of an abnormal (the
/// stun swirl, the poison tint, the silence mark). Purely cosmetic: the
/// mechanics live in [`super::effect_flag`] and the effect handlers, while this is
/// what the client renders over the character.
///
/// The **full** enum in Java's own order, `(name, client id)`, generated from
/// the Java source. It used to stop at id 38, which silently dropped 102 of the
/// names the dist's own skills reference (`AURA_BUFF`, `ABSORB_SHIELD`, the
/// `*_CHANGE` grade glows…) — the skill parsed, but its visual never reached
/// the client. Order matters beyond lookup: `//ave_abnormal`'s menu pages
/// through `AbnormalVisualEffect.values()`, which is exactly this sequence.
/// `VP_KEEP` shares client id 29 with `VP_UP` in Java, comment and all.
pub const ABNORMAL_VISUAL_EFFECTS: &[(&str, i16)] = &[
    ("DOT_BLEEDING", 1),
    ("DOT_POISON", 2),
    ("DOT_FIRE", 3),
    ("DOT_WATER", 4),
    ("DOT_WIND", 5),
    ("DOT_SOIL", 6),
    ("STUN", 7),
    ("SLEEP", 8),
    ("SILENCE", 9),
    ("ROOT", 10),
    ("PARALYZE", 11),
    ("FLESH_STONE", 12),
    ("DOT_MP", 13),
    ("BIG_HEAD", 14),
    ("DOT_FIRE_AREA", 15),
    ("CHANGE_TEXTURE", 16),
    ("BIG_BODY", 17),
    ("FLOATING_ROOT", 18),
    ("DANCE_ROOT", 19),
    ("GHOST_STUN", 20),
    ("STEALTH", 21),
    ("SEIZURE1", 22),
    ("SEIZURE2", 23),
    ("MAGIC_SQUARE", 24),
    ("FREEZING", 25),
    ("SHAKE", 26),
    ("ULTIMATE_DEFENCE", 28),
    ("VP_UP", 29),
    // Java gives VP_KEEP the same 29 as VP_UP and flags that it does not know
    // the real id; carried as shipped.
    ("VP_KEEP", 29),
    ("REAL_TARGET", 30),
    ("DEATH_MARK", 31),
    ("TURN_FLEE", 32),
    ("INVINCIBILITY", 33),
    ("AIR_BATTLE_SLOW", 34),
    ("AIR_BATTLE_ROOT", 35),
    ("CHANGE_WP", 36),
    ("CHANGE_HAIR_G", 37), // Gold Afro
    ("CHANGE_HAIR_P", 38), // Pink Afro
    ("CHANGE_HAIR_B", 39), // Black Afro
    ("UNKNOWN_40", 40),
    ("STIGMA_OF_SILEN", 41),
    ("SPEED_DOWN", 42),
    ("FROZEN_PILLAR", 43),
    ("CHANGE_VES_S", 44),
    ("CHANGE_VES_C", 45),
    ("CHANGE_VES_D", 46),
    ("TIME_BOMB", 47),
    ("MP_SHIELD", 48),
    ("AIRBIND", 49),
    ("CHANGEBODY", 50),
    ("KNOCKDOWN", 51),
    ("NAVIT_ADVENT", 52),
    ("KNOCKBACK", 53),
    ("CHANGE_7ANNIVERSARY", 54),
    ("ON_SPOT_MOVEMENT", 55),
    ("DEPORT", 56),
    ("AURA_BUFF", 57),
    ("AURA_BUFF_SELF", 58),
    ("AURA_DEBUFF", 59),
    ("AURA_DEBUFF_SELF", 60),
    ("HURRICANE", 61),
    ("HURRICANE_SELF", 62),
    ("BLACK_MARK", 63),
    ("BR_SOUL_AVATAR", 64),
    ("CHANGE_GRADE_B", 65),
    ("BR_BEAM_SWORD_ONEHAND", 66),
    ("BR_BEAM_SWORD_DUAL", 67),
    ("NO_CHAT", 68),
    ("HERB_PA_UP", 69),
    ("HERB_MA_UP", 70),
    ("SEED_TALISMAN1", 71),
    ("SEED_TALISMAN2", 72),
    ("SEED_TALISMAN3", 73),
    ("SEED_TALISMAN4", 74),
    ("SEED_TALISMAN5", 75),
    ("SEED_TALISMAN6", 76),
    ("CURIOUS_HOUSE", 77),
    ("NGRADE_CHANGE", 78),
    ("DGRADE_CHANGE", 79),
    ("CGRADE_CHANGE", 80),
    ("BGRADE_CHANGE", 81),
    ("AGRADE_CHANGE", 82),
    ("SWEET_ICE_FLAKES", 83),
    ("FANTASY_ICE_FLAKES", 84),
    ("CHANGE_XMAS", 85),
    ("CARD_PC_DECO", 86),
    ("CHANGE_DINOS", 87),
    ("CHANGE_VALENTINE", 88),
    ("CHOCOLATE", 89),
    ("CANDY", 90),
    ("COOKIE", 91),
    ("STARS_0", 92),
    ("STARS_1", 93),
    ("STARS_2", 94),
    ("STARS_3", 95),
    ("STARS_4", 96),
    ("STARS_5", 97),
    ("DUELING", 98),
    ("FREEZING2", 99),
    ("CHANGE_YOGI", 100),
    ("YOGI", 101),
    ("MUSICAL_NOTE_YELLOW", 102),
    ("MUSICAL_NOTE_BLUE", 103),
    ("MUSICAL_NOTE_GREEN", 104),
    ("TENTH_ANNIVERSARY", 105),
    ("XMAS_SOCKS", 106),
    ("XMAS_TREE", 107),
    ("XMAS_SNOWMAN", 108),
    ("OTHELL_ROGUE_BLUFF", 109),
    ("HE_PROTECT", 110),
    ("SU_SUMCROSS", 111),
    ("WIND_STUN", 112),
    ("STORM_SIGN2", 113),
    ("STORM_SIGN1", 114),
    ("WIND_BLEND", 115),
    ("DECEPTIVE_BLINK", 116),
    ("WIND_HIDE", 117),
    ("PSY_POWER", 118),
    ("SQUALL", 119),
    ("WIND_ILLUSION", 120),
    ("SAYHA_FURY", 121),
    ("HIDE4", 123),
    ("PMENTAL_TRAIL", 124),
    ("HOLD_LIGHTING", 125),
    ("GRAVITY_SPACE_3", 126),
    ("SPACEREF", 127),
    ("HE_ASPECT", 128),
    ("RUNWAY_ARMOR1", 129),
    ("RUNWAY_ARMOR2", 130),
    ("RUNWAY_ARMOR3", 131),
    ("RUNWAY_ARMOR4", 132),
    ("RUNWAY_ARMOR5", 133),
    ("RUNWAY_ARMOR6", 134),
    ("RUNWAY_WEAPON1", 135),
    ("RUNWAY_WEAPON2", 136),
    ("PALADIN_PROTECTION", 141),
    ("SENTINEL_PROTECTION", 142),
    ("REAL_TARGET_2", 143),
    ("DIVINITY", 144),
    ("SHILLIEN_PROTECTION", 145),
    ("EVENT_STARS_0", 146),
    ("EVENT_STARS_1", 147),
    ("EVENT_STARS_2", 148),
    ("EVENT_STARS_3", 149),
    ("EVENT_STARS_4", 150),
    ("EVENT_STARS_5", 151),
    ("ABSORB_SHIELD", 152),
    ("PHOENIX_AURA", 153),
    ("REVENGE_AURA", 154),
    ("EVAS_AURA", 155),
    ("TEMPLAR_AURA", 156),
    ("LONG_BLOW", 157),
    ("WIDE_SWORD", 158),
    ("BIG_FIST", 159),
    ("SHADOW_STEP", 160),
    ("TORNADO", 161),
    ("SNOW_SLOW", 162),
    ("SNOW_HOLD", 163),
    ("TORNADO_SLOW", 165),
    ("ASTATINE_WATER", 166),
    ("BIG_BODY_COMBINATION_CAT_NPC", 167),
    ("BIG_BODY_COMBINATION_UNICORN_NPC", 168),
    ("BIG_BODY_COMBINATION_DEMON_NPC", 169),
    ("BIG_BODY_COMBINATION_CAT_PC", 170),
    ("BIG_BODY_COMBINATION_UNICORN_PC", 171),
    ("BIG_BODY_COMBINATION_DEMON_PC", 172),
    ("BIG_BODY_2", 173),
    ("BIG_BODY_3", 174),
    ("PIRATE_SUIT", 175),
    ("DARK_ASSASSIN_SUIT", 176),
    ("WHITE_ASSASSIN_SUIT", 177),
    ("AVE_DRAGON_ULTIMATE", 181),
    ("INFINITE_SHIELD1_AVE", 183),
    ("INFINITE_SHIELD2_AVE", 184),
    ("INFINITE_SHIELD3_AVE", 185),
    ("INFINITE_SHIELD4_AVE", 186),
    ("AVE_ABSORB2_SHIELD", 187),
    ("TALI_DECO_BAIUM", 190),
    ("CHANGESHAPE_TRANSFORM", 193),
    ("ANGRY_GOLEM_AVE", 194),
    ("WA_UNBREAKABLE_SONIC_AVE", 195),
    ("HEROIC_HOLY_AVE", 196),
    ("HEROIC_SILENCE_AVE", 197),
    ("HEROIC_FEAR_AVE_1", 198),
    ("HEROIC_FEAR_AVE_2", 199),
    ("AVE_BROOCH", 200),
    ("INFINITE_SHIELD4_AVE_2", 206),
    ("CHANGESHAPE_TRANSFORM_1", 207),
    ("CHANGESHAPE_TRANSFORM_2", 208),
    ("CHANGESHAPE_TRANSFORM_3", 209),
    ("CHANGESHAPE_TRANSFORM_4", 210),
    ("RO_COUNTER_TRASPIE", 215),
    ("RO_GHOST_REFLECT", 217),
    ("CHANGESHAPE_TRANSFORM_5", 218),
    ("ICE_ELEMENTALDESTROY", 219),
    ("DRAGON_ULTIMATE", 700),
    ("CHANGE_HALLOWEEN", 1000),
    ("BR_Y_1_ACCESSORY_R_RING", 10001),
    ("BR_Y_1_ACCESSORY_EARRING", 10002),
    ("BR_Y_1_ACCESSORY_NECKRACE", 10003),
    ("BR_Y_2_ACCESSORY_R_RING", 10004),
    ("BR_Y_2_ACCESSORY_EARRING", 10005),
    ("BR_Y_2_ACCESSORY_NECKRACE", 10006),
    ("BR_Y_3_ACCESSORY_R_RING", 10007),
    ("BR_Y_3_ACCESSORY_EARRING", 10008),
    ("BR_Y_3_ACCESSORY_NECKRACE", 10009),
];

/// Name → client id, or `None` for a name the enum doesn't have — which is
/// simply not shown, matching Java's `findByName` + warning.
pub fn abnormal_visual_client_id(name: &str) -> Option<i16> {
    ABNORMAL_VISUAL_EFFECTS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|&(_, id)| id)
}

/// `AbnormalVisualEffect.STEALTH.getClientId()` — GM invisibility's translucent
/// glow, appended by Java whenever `isInvisible()`.
pub const STEALTH_CLIENT_ID: i16 = 21;

/// `AbnormalType.getClientId()` — the id the client groups a buff icon by, as
/// written into `AbnormalStatusUpdate` and `ExAbnormalStatusUpdateFromTarget`.
///
/// Generated from Java's `AbnormalType` enum: it declares 535 constants,
/// of which **309** carry a real id and the rest are `-1` (`NONE`). Only the
/// 309 are listed; everything else — unknown names included — falls through
/// to `-1`, which is exactly Java's default for an unmapped type.
///
/// This used to map **two** names, so all but two buffs told the client `NONE`.
/// Kept in sync by `abnormal_type_client_ids_match_java`.
pub fn abnormal_type_client_id(name: &str) -> i32 {
    match name {
        "AB_HAWK_EYE" => 0,
        "ALL_ATTACK_DOWN" => 1,
        "ALL_ATTACK_UP" => 2,
        "ALL_SPEED_DOWN" => 3,
        "ALL_SPEED_UP" => 4,
        "ANTARAS_DEBUFF" => 5,
        "ARMOR_EARTH" => 6,
        "ARMOR_FIRE" => 7,
        "ARMOR_HOLY" => 8,
        "ARMOR_UNHOLY" => 9,
        "ARMOR_WATER" => 10,
        "ARMOR_WIND" => 11,
        "ATTACK_SPEED_UP_BOW" => 12,
        "ATTACK_TIME_DOWN" => 13,
        "ATTACK_TIME_UP" => 14,
        "AVOID_DOWN" => 15,
        "AVOID_UP" => 16,
        "AVOID_UP_SPECIAL" => 17,
        "BERSERKER" => 18,
        "BIG_BODY" => 19,
        "BIG_HEAD" => 20,
        "BLEEDING" => 21,
        "BOW_RANGE_UP" => 22,
        "BUFF_QUEEN_OF_CAT" => 23,
        "BUFF_UNICORN_SERAPHIM" => 24,
        "CANCEL_PROB_DOWN" => 25,
        "CASTING_TIME_DOWN" => 26,
        "CASTING_TIME_UP" => 27,
        "CHEAP_MAGIC" => 28,
        "CRITICAL_DMG_DOWN" => 29,
        "CRITICAL_DMG_UP" => 30,
        "CRITICAL_PROB_DOWN" => 31,
        "CRITICAL_PROB_UP" => 32,
        "DANCE_OF_AQUA_GUARD" => 33,
        "DANCE_OF_CONCENTRATION" => 34,
        "DANCE_OF_EARTH_GUARD" => 35,
        "DANCE_OF_FIRE" => 36,
        "DANCE_OF_FURY" => 37,
        "DANCE_OF_INSPIRATION" => 38,
        "DANCE_OF_LIGHT" => 39,
        "DANCE_OF_MYSTIC" => 40,
        "DANCE_OF_PROTECTION" => 41,
        "DANCE_OF_SHADOW" => 42,
        "DANCE_OF_SIREN" => 43,
        "DANCE_OF_VAMPIRE" => 44,
        "DANCE_OF_WARRIOR" => 45,
        "DEBUFF_NIGHTSHADE" => 46,
        "DEBUFF_SHIELD" => 47,
        "DECREASE_WEIGHT_PENALTY" => 48,
        "DERANGEMENT" => 49,
        "DETECT_WEAKNESS" => 50,
        "DMG_SHIELD" => 51,
        "DOT_ATTR" => 52,
        "DOT_MP" => 53,
        "DRAGON_BREATH" => 54,
        "DUELIST_SPIRIT" => 55,
        "FATAL_POISON" => 56,
        "FISHING_MASTERY_DOWN" => 57,
        "FLY_AWAY" => 58,
        "FOCUS_DAGGER" => 59,
        "HEAL_EFFECT_DOWN" => 60,
        "HEAL_EFFECT_UP" => 61,
        "HERO_BUFF" => 62,
        "HERO_DEBUFF" => 63,
        "HIT_DOWN" => 64,
        "HIT_UP" => 65,
        "HOLY_ATTACK" => 66,
        "HP_RECOVER" => 67,
        "HP_REGEN_DOWN" => 68,
        "HP_REGEN_UP" => 69,
        "LIFE_FORCE_ORC" => 70,
        "LIFE_FORCE_OTHERS" => 71,
        "MAGIC_CRITICAL_UP" => 72,
        "MAJESTY" => 73,
        "MAX_BREATH_UP" => 74,
        "MAX_HP_DOWN" => 75,
        "MAX_HP_UP" => 76,
        "MAX_MP_UP" => 77,
        "MA_DOWN" => 78,
        "MA_UP" => 79,
        "MA_UP_HERB" => 80,
        "MD_DOWN" => 81,
        "MD_UP" => 82,
        "MD_UP_ATTR" => 83,
        "MIGHT_MORTAL" => 84,
        "MP_COST_DOWN" => 85,
        "MP_COST_UP" => 86,
        "MP_RECOVER" => 87,
        "MP_REGEN_UP" => 88,
        "MULTI_BUFF" => 89,
        "MULTI_DEBUFF" => 90,
        "PARALYZE" => 91,
        "PA_DOWN" => 92,
        "PA_PD_UP" => 93,
        "PA_UP" => 94,
        "PA_UP_HERB" => 95,
        "PA_UP_SPECIAL" => 96,
        "PD_DOWN" => 97,
        "PD_UP" => 98,
        "PD_UP_BOW" => 99,
        "PD_UP_SPECIAL" => 100,
        "PINCH" => 101,
        "POISON" => 102,
        "POLEARM_ATTACK" => 103,
        "POSSESSION" => 104,
        "PRESERVE_ABNORMAL" => 105,
        "PUBLIC_SLOT" => 106,
        "RAGE_MIGHT" => 107,
        "REDUCE_DROP_PENALTY" => 108,
        "REFLECT_ABNORMAL" => 109,
        "RESIST_BLEEDING" => 110,
        "RESIST_DEBUFF_DISPEL" => 111,
        "RESIST_DERANGEMENT" => 112,
        "RESIST_HOLY_UNHOLY" => 113,
        "RESIST_POISON" => 114,
        "RESIST_SHOCK" => 115,
        "RESIST_SPIRITLESS" => 116,
        "REUSE_DELAY_DOWN" => 117,
        "REUSE_DELAY_UP" => 118,
        "ROOT_PHYSICALLY" => 119,
        "ROOT_MAGICALLY" => 120,
        "SHIELD_DEFENCE_UP" => 121,
        "SHIELD_PROB_UP" => 122,
        "SILENCE" => 123,
        "SILENCE_ALL" => 124,
        "SILENCE_PHYSICAL" => 125,
        "SLEEP" => 126,
        "SNIPE" => 127,
        "SONG_OF_CHAMPION" => 128,
        "SONG_OF_EARTH" => 129,
        "SONG_OF_FLAME_GUARD" => 130,
        "SONG_OF_HUNTER" => 131,
        "SONG_OF_INVOCATION" => 132,
        "SONG_OF_LIFE" => 133,
        "SONG_OF_MEDITATION" => 134,
        "SONG_OF_RENEWAL" => 135,
        "SONG_OF_STORM_GUARD" => 136,
        "SONG_OF_VENGEANCE" => 137,
        "SONG_OF_VITALITY" => 138,
        "SONG_OF_WARDING" => 139,
        "SONG_OF_WATER" => 140,
        "SONG_OF_WIND" => 141,
        "SPA_DISEASE_A" => 142,
        "SPA_DISEASE_B" => 143,
        "SPA_DISEASE_C" => 144,
        "SPA_DISEASE_D" => 145,
        "SPEED_DOWN" => 146,
        "SPEED_UP" => 147,
        "SPEED_UP_SPECIAL" => 148,
        "SSQ_TOWN_BLESSING" => 149,
        "SSQ_TOWN_CURSE" => 150,
        "STEALTH" => 151,
        "STUN" => 152,
        "THRILL_FIGHT" => 153,
        "TOUCH_OF_DEATH" => 154,
        "TOUCH_OF_LIFE" => 155,
        "TURN_FLEE" => 156,
        "TURN_PASSIVE" => 157,
        "TURN_STONE" => 158,
        "ULTIMATE_BUFF" => 159,
        "ULTIMATE_DEBUFF" => 160,
        "VALAKAS_ITEM" => 161,
        "VAMPIRIC_ATTACK" => 162,
        "WATCHER_GAZE" => 163,
        "RESURRECTION_SPECIAL" => 164,
        "COUNTER_SKILL" => 165,
        "AVOID_SKILL" => 166,
        "CP_UP" => 167,
        "CP_DOWN" => 168,
        "CP_REGEN_UP" => 169,
        "CP_REGEN_DOWN" => 170,
        "INVINCIBILITY" => 171,
        "ABNORMAL_INVINCIBILITY" => 172,
        "PHYSICAL_STANCE" => 173,
        "MAGICAL_STANCE" => 174,
        "COMBINATION" => 175,
        "ANESTHESIA" => 176,
        "CRITICAL_POISON" => 177,
        "SEIZURE_PENALTY" => 178,
        "ABNORMAL_ITEM" => 179,
        "SEIZURE_A" => 180,
        "SEIZURE_B" => 181,
        "SEIZURE_C" => 182,
        "FORCE_MEDITATION" => 183,
        "MIRAGE" => 184,
        "POTION_OF_GENESIS" => 185,
        "PVP_DMG_UP" => 186,
        "PVP_DMG_DOWN" => 187,
        "IRON_SHIELD" => 188,
        "TRANSFER_DAMAGE" => 189,
        "SONG_OF_ELEMENTAL" => 190,
        "DANCE_OF_ALIGNMENT" => 191,
        "ARCHER_SPECIAL" => 192,
        "SPOIL_BOMB" => 193,
        "FIRE_DOT" => 194,
        "WATER_DOT" => 195,
        "WIND_DOT" => 196,
        "EARTH_DOT" => 197,
        "HEAL_POWER_UP" => 198,
        "RECHARGE_UP" => 199,
        "NORMAL_ATTACK_BLOCK" => 200,
        "DISARM" => 201,
        "DEATH_MARK" => 202,
        "KAMAEL_SPECIAL" => 203,
        "TRANSFORM" => 204,
        "DARK_SEED" => 205,
        "REAL_TARGET" => 206,
        "FREEZING" => 207,
        "TIME_CHECK" => 208,
        "MA_MD_UP" => 209,
        "DEATH_CLACK" => 210,
        "HOT_GROUND" => 211,
        "EVIL_BLOOD" => 212,
        "ALL_REGEN_UP" => 213,
        "ALL_REGEN_DOWN" => 214,
        "IRON_SHIELD_I" => 215,
        "ARCHER_SPECIAL_I" => 216,
        "T_CRT_RATE_UP" => 217,
        "T_CRT_RATE_DOWN" => 218,
        "T_CRT_DMG_UP" => 219,
        "T_CRT_DMG_DOWN" => 220,
        "INSTINCT" => 221,
        "OBLIVION" => 222,
        "WEAK_CONSTITUTION" => 223,
        "THIN_SKIN" => 224,
        "ENERVATION" => 225,
        "SPITE" => 226,
        "MENTAL_IMPOVERISH" => 227,
        "ATTRIBUTE_POTION" => 228,
        "TALISMAN" => 229,
        "MULTI_DEBUFF_FIRE" => 230,
        "MULTI_DEBUFF_WATER" => 231,
        "MULTI_DEBUFF_WIND" => 232,
        "MULTI_DEBUFF_EARTH" => 233,
        "MULTI_DEBUFF_HOLY" => 234,
        "MULTI_DEBUFF_UNHOLY" => 235,
        "LIFE_FORCE_KAMAEL" => 236,
        "MA_UP_SPECIAL" => 237,
        "PK_PROTECT" => 238,
        "MAXIMUM_ABILITY" => 239,
        "TARGET_LOCK" => 240,
        "PROTECTION" => 241,
        "WILL" => 242,
        "SEED_OF_KNIGHT" => 243,
        "EXPOSE_WEAK_POINT" => 244,
        "FORCE_OF_DESTRUCTION" => 245,
        "ELEMENTAL_ARMOR" => 246,
        "SUMMON_CONDITION" => 247,
        "IMPROVE_PA_PD_UP" => 248,
        "IMPROVE_MA_MD_UP" => 249,
        "IMPROVE_HP_MP_UP" => 250,
        "IMPROVE_CRT_RATE_DMG_UP" => 251,
        "IMPROVE_SHIELD_RATE_DEFENCE_UP" => 252,
        "IMPROVE_SPEED_AVOID_UP" => 253,
        "LIMIT" => 254,
        "MULTI_DEBUFF_SOUL" => 255,
        "CURSE_LIFE_FLOW" => 256,
        "BETRAYAL_MARK" => 257,
        "TRANSFORM_HANGOVER" => 258,
        "TRANSFORM_SCRIFICE" => 259,
        "SONG_OF_WINDSTORM" => 260,
        "DANCE_OF_BLADESTORM" => 261,
        "IMPROVE_VAMPIRIC_HASTE" => 262,
        "WEAPON_MASTERY" => 263,
        "APELLA" => 264,
        "TRANSFORM_SCRIFICE_P" => 265,
        "SUB_TRIGGER_HASTE" => 266,
        "SUB_TRIGGER_DEFENCE" => 267,
        "SUB_TRIGGER_CRT_RATE_UP" => 268,
        "SUB_TRIGGER_SPIRIT" => 269,
        "MIRAGE_TRAP" => 270,
        "DEATH_PENALTY" => 271,
        "ENTRY_FOR_GAME" => 272,
        "BLOOD_CONSTRACT" => 273,
        "DWARF_BUFF" => 274,
        "EVASION_BUFF" => 275,
        "SOUL_SHIELD" => 276,
        "BR_UTHANKA_BUFF" => 277,
        "FIELD_RAID_BUFF1" => 278,
        "PD_UP_DMAGIC" => 279,
        "PREMIUM_BUFF" => 280,
        "RUNWAY_ARMOR" => 281,
        "RUNWAY_WEAPON" => 282,
        "G_EV_BUFF1" => 283,
        "MAX" => 284,
        "AIRBIND" => 365,
        "KNOCKDOWN" => 367,
        "EARTHWORM_DEBUFF" => 424,
        "SYNERGY_SIGEL" => 433,
        "SYNERGY_TIR" => 434,
        "SYNERGY_OTHEL" => 435,
        "SYNERGY_YR" => 436,
        "SYNERGY_FEOH" => 437,
        "SYNERGY_IS" => 438,
        "SYNERGY_WYNN" => 439,
        "SYNERGY_EOLH" => 440,
        "AGATHION_SONG_DANCE" => 444,
        "SYNERGY_PARTY_BUF" => 465,
        "POTION_OF_PROTECTION" => 552,
        "SYNERGY_LENKER" => 589,
        "SYNERGY_SEER" => 590,
        "INSIDE_POSITION" => 593,
        "STEEL_MIND" => 596,
        "SIGEL_SHIELD" => 597,
        "HELLBOUND_BUFF" => 598,
        "MAPHR_AURA" => 599,
        "SAYHA_AURA" => 600,
        "EVAS_DEBUFF" => 601,
        "RIGHT_SIDESTEP" => 602,
        _ => -1,
    }
}

// The debuff landing-chance formula is unit-tested in `formulas.rs`
// (`effect_land_rate_clamps_and_special_cases`); the caster-facing chance line
// and the resist roll have end-to-end tests in `game_loop::tests::skills_tests`
// (`single_target_debuff_lands_and_reports_chance` /
// `single_target_debuff_resisted_leaves_target_and_reports`).

#[cfg(test)]
mod abnormal_type_tests {
    use super::abnormal_type_client_id;

    /// The table is generated from Java's `AbnormalType` enum, so it is checked
    /// against that enum rather than against a copy of itself.
    ///
    /// Parsing the reference at test time is the point: a hand-maintained list
    /// drifts silently, and this one had drifted all the way down to **two**
    /// entries while every other buff told the client `NONE`.
    ///
    /// Skipped (not failed) when the Java tree is not beside this repo, so the
    /// suite still runs standalone.
    #[test]
    fn abnormal_type_client_ids_match_java() {
        // Walk up from this crate looking for a sibling `interlude_classic`.
        // A fixed `../../../` breaks inside a git worktree (this repo's own
        // workflow), where it resolves under `.claude/worktrees/` — and the
        // skip-if-absent branch then hides the breakage: the test passed even
        // with a deliberately wrong entry until this was fixed.
        const REL: &str = "java/org/l2jmobius/gameserver/model/skill/AbnormalType.java";
        let src = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .map(|dir| dir.join("interlude_classic").join(REL))
            .find_map(|p| std::fs::read_to_string(p).ok());
        let Some(src) = src else {
            eprintln!("skipping: no sibling interlude_classic checkout found");
            return;
        };
        let body = &src[src.find("NONE(-1)").expect("the enum starts at NONE")
            ..src
                .find("private final int _clientId")
                .expect("the field follows")];

        let mut checked = 0usize;
        let mut with_id = 0usize;
        for line in body.lines() {
            let l = line.trim();
            let Some(open) = l.find('(') else { continue };
            let name = &l[..open];
            if name.is_empty()
                || !name
                    .chars()
                    .all(|c| c.is_ascii_uppercase() || c == '_' || c.is_ascii_digit())
            {
                continue;
            }
            let Some(close) = l[open..].find(')') else {
                continue;
            };
            let Ok(expected) = l[open + 1..open + close].parse::<i32>() else {
                continue;
            };
            assert_eq!(
                abnormal_type_client_id(name),
                expected,
                "{name} disagrees with Java's AbnormalType"
            );
            checked += 1;
            if expected != -1 {
                with_id += 1;
            }
        }
        assert!(
            checked > 500 && with_id > 300,
            "sanity: parsed {checked} constants, {with_id} with a real id — \
             a parse that silently matched nothing would pass every assertion above"
        );
        assert_eq!(
            abnormal_type_client_id("NOT_A_REAL_ABNORMAL"),
            -1,
            "an unmapped name falls through to NONE, as Java's default does"
        );
    }
}
