[package]
name = "gameserver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
commons = { path = "../commons" }
tokio.workspace = true
bytes.workspace = true
sqlx.workspace = true
rand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
quick-xml.workspace = true
if-addrs.workspace = true

[dev-dependencies]
serde_json = "1"
commons = { path = "../commons" }
loginserver = { path = "../loginserver" }
num-bigint-dig.workspace = true
