//! Outbound email over SMTP (Amazon SES in production).
//!
//! Two messages exist, and both carry a signed one-time link generated by
//! `auth::token`: verify an email address, and reset a password. The token is
//! the security boundary — this module only has to deliver it.
//!
//! **Disabled by default.** With no SMTP credentials configured the mailer logs
//! the link instead of sending it, which is what makes local development work
//! without an SES account. Production is expected to configure it; `main`
//! warns at boot when it is not.

use lettre::message::{header::ContentType, Mailbox, MultiPart, SinglePart};
use lettre::transport::smtp::authentication::Credentials;
use lettre::{AsyncSmtpTransport, AsyncTransport, Message, Tokio1Executor};

use crate::config::DashboardConfig;

#[derive(Debug, thiserror::Error)]
pub enum MailError {
    #[error("invalid email address: {0}")]
    Address(String),
    #[error("could not build the message: {0}")]
    Build(String),
    #[error("SMTP delivery failed: {0}")]
    Send(String),
}

#[derive(Clone)]
pub struct Mailer {
    /// `None` when SMTP is unconfigured — links get logged instead of sent.
    transport: Option<AsyncSmtpTransport<Tokio1Executor>>,
    from: Option<Mailbox>,
    site_name: String,
}

impl Mailer {
    /// Builds a mailer, or a logging no-op when SMTP is not fully configured.
    ///
    /// All of host, username and password are required: a half-configured
    /// mailer would fail at send time, on the request path, rather than at boot.
    pub fn from_config(config: &DashboardConfig) -> Self {
        let configured = !config.smtp_host.is_empty()
            && !config.smtp_username.is_empty()
            && !config.smtp_password.is_empty();

        if !configured {
            return Self::disabled();
        }

        let from = match config.smtp_from.parse::<Mailbox>() {
            Ok(mailbox) => mailbox,
            Err(e) => {
                tracing::error!(
                    "SmtpFrom is not a valid address ({}): {e}. Email is disabled.",
                    config.smtp_from
                );
                return Self::disabled();
            }
        };

        // SES requires TLS on every port. See `uses_implicit_tls`.
        let builder = if uses_implicit_tls(config.smtp_port) {
            AsyncSmtpTransport::<Tokio1Executor>::relay(&config.smtp_host)
        } else {
            AsyncSmtpTransport::<Tokio1Executor>::starttls_relay(&config.smtp_host)
        };

        let transport = match builder {
            Ok(builder) => builder
                .port(config.smtp_port)
                .credentials(Credentials::new(
                    config.smtp_username.clone(),
                    config.smtp_password.clone(),
                ))
                .build(),
            Err(e) => {
                tracing::error!("cannot build the SMTP transport: {e}. Email is disabled.");
                return Self::disabled();
            }
        };

        tracing::info!(
            "email enabled: {}:{} as {}",
            config.smtp_host,
            config.smtp_port,
            config.smtp_from
        );

        Self {
            transport: Some(transport),
            from: Some(from),
            site_name: site_name_from(&config.site_base_url),
        }
    }

    fn disabled() -> Self {
        Self {
            transport: None,
            from: None,
            site_name: "BattleCrab".to_string(),
        }
    }

    pub fn is_enabled(&self) -> bool {
        self.transport.is_some()
    }

    /// Confirm a new address. The link is what actually writes
    /// `accounts.email`, so an address only becomes stored once it is proven.
    pub async fn send_email_verification(
        &self,
        to: &str,
        login: &str,
        link: &str,
    ) -> Result<(), MailError> {
        let subject = format!("Confirm your email for {}", self.site_name);
        let text = format!(
            "Hi {login},\n\n\
             Confirm this address so it can be used to reset your {site} password:\n\n\
             {link}\n\n\
             The link is valid for 24 hours. Until you use it, nothing changes on your account.\n\n\
             If you didn't ask for this, you can ignore this email.\n",
            site = self.site_name
        );
        self.send(to, &subject, text, link, "Confirm email address")
            .await
    }

    /// Reset a forgotten password. The link stops working the moment the
    /// password changes, so it is single-use by construction.
    pub async fn send_password_reset(
        &self,
        to: &str,
        login: &str,
        link: &str,
    ) -> Result<(), MailError> {
        let subject = format!("Reset your {} password", self.site_name);
        let text = format!(
            "Hi {login},\n\n\
             Someone asked to reset the password for your {site} account. Use this link:\n\n\
             {link}\n\n\
             The link is valid for 1 hour and can only be used once.\n\n\
             If this wasn't you, ignore this email — your password stays as it is.\n",
            site = self.site_name
        );
        self.send(to, &subject, text, link, "Reset password").await
    }

    async fn send(
        &self,
        to: &str,
        subject: &str,
        text: String,
        link: &str,
        button_label: &str,
    ) -> Result<(), MailError> {
        let (Some(transport), Some(from)) = (&self.transport, &self.from) else {
            // Development path: no SMTP configured. Log at WARN so the link is
            // visible at the default log level — it is the only way to complete
            // the flow locally.
            tracing::warn!("email disabled; {subject} link for {to}: {link}");
            return Ok(());
        };

        let message = build_message(
            from.clone(),
            to,
            subject,
            &text,
            &html_body(&self.site_name, &text, link, button_label),
        )?;

        transport
            .send(message)
            .await
            .map_err(|e| MailError::Send(format!("{e}")))?;

        Ok(())
    }
}

/// Ports 465 and 2465 expect TLS from the first byte; 25, 587 and 2587 start
/// plaintext and upgrade with STARTTLS. Choosing wrong either hangs the
/// connection or fails the handshake, so it is derived rather than configured.
fn uses_implicit_tls(port: u16) -> bool {
    matches!(port, 465 | 2465)
}

/// Builds the MIME message: a `multipart/alternative` with text first.
///
/// Plain text first because every client renders it, and because an
/// HTML-only message scores worse with spam filters — which matters when the
/// mail carries the only link a locked-out user can use.
fn build_message(
    from: Mailbox,
    to: &str,
    subject: &str,
    text: &str,
    html: &str,
) -> Result<Message, MailError> {
    let to: Mailbox = to.parse().map_err(|e| MailError::Address(format!("{e}")))?;

    Message::builder()
        .from(from)
        .to(to)
        .subject(subject)
        .multipart(
            MultiPart::alternative()
                .singlepart(
                    SinglePart::builder()
                        .header(ContentType::TEXT_PLAIN)
                        .body(text.to_string()),
                )
                .singlepart(
                    SinglePart::builder()
                        .header(ContentType::TEXT_HTML)
                        .body(html.to_string()),
                ),
        )
        .map_err(|e| MailError::Build(format!("{e}")))
}

/// Minimal, inline-styled HTML — email clients strip <style> blocks and
/// external CSS, so anything more elaborate degrades unpredictably.
fn html_body(site: &str, text: &str, link: &str, button_label: &str) -> String {
    let intro = text
        .lines()
        .take_while(|line| !line.contains("http"))
        .map(|line| html_escape(line.trim()))
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join("<br>");

    format!(
        r#"<!doctype html>
<html><body style="margin:0;padding:24px;background:#eef4fd;font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;color:#0a1a30">
  <div style="max-width:480px;margin:0 auto;background:#fff;border-radius:16px;padding:28px">
    <p style="margin:0 0 18px;font-size:18px;font-weight:700">{site}</p>
    <p style="margin:0 0 22px;font-size:15px;line-height:1.55">{intro}</p>
    <p style="margin:0 0 22px">
      <a href="{link}" style="display:inline-block;background:#ffd700;color:#00122a;text-decoration:none;font-weight:700;font-size:15px;padding:12px 22px;border-radius:10px">{button_label}</a>
    </p>
    <p style="margin:0;font-size:12px;color:#4a5f7e;line-height:1.5">
      If the button doesn't work, copy this into your browser:<br>
      <span style="word-break:break-all">{link}</span>
    </p>
  </div>
</body></html>"#
    )
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// "https://battlecrab.com" -> "Battlecrab", for use in subjects and greetings.
fn site_name_from(site_base_url: &str) -> String {
    let host = site_base_url
        .trim_start_matches("https://")
        .trim_start_matches("http://")
        .split('/')
        .next()
        .unwrap_or("")
        .split(':')
        .next()
        .unwrap_or("");

    let label = host
        .strip_prefix("www.")
        .unwrap_or(host)
        .split('.')
        .next()
        .unwrap_or("");

    if label.is_empty() {
        return "BattleCrab".to_string();
    }
    let mut chars = label.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => "BattleCrab".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn site_name_is_derived_from_the_site_url() {
        assert_eq!(site_name_from("https://battlecrab.com"), "Battlecrab");
        assert_eq!(site_name_from("https://www.battlecrab.com"), "Battlecrab");
        assert_eq!(site_name_from("http://localhost:3000"), "Localhost");
        assert_eq!(site_name_from(""), "BattleCrab");
    }

    #[test]
    fn html_body_escapes_and_keeps_the_link_clickable() {
        let html = html_body(
            "Site",
            "Hi <script>\nuse http://x",
            "https://x/y?t=1&b=2",
            "Go",
        );
        assert!(
            html.contains("&lt;script&gt;"),
            "must escape injected markup"
        );
        assert!(
            html.contains("https://x/y?t=1&b=2"),
            "link must survive verbatim"
        );
        assert!(html.contains(">Go<"));
    }

    #[test]
    fn html_body_stops_the_intro_before_the_raw_link() {
        // The URL is rendered as a button and a copyable span, not inline prose.
        let html = html_body(
            "Site",
            "Line one\n\nhttps://example.com/tok\n\ntrailing",
            "https://example.com/tok",
            "Go",
        );
        let intro_end = html.find("<a href").unwrap();
        assert!(!html[..intro_end].contains("example.com"));
    }

    #[test]
    fn tls_mode_is_chosen_by_port() {
        // SES: 465/2465 are TLS-wrapped, the rest upgrade via STARTTLS.
        assert!(uses_implicit_tls(465));
        assert!(uses_implicit_tls(2465));
        assert!(!uses_implicit_tls(587));
        assert!(!uses_implicit_tls(25));
        assert!(!uses_implicit_tls(2587));
    }

    #[test]
    fn message_carries_both_alternatives_and_the_link() {
        let from: Mailbox = "BattleCrab <no-reply@battlecrab.com>".parse().unwrap();
        let msg = build_message(
            from,
            "player@example.com",
            "Reset your password",
            "text version https://site/reset?token=abc",
            "<p>html version</p>",
        )
        .expect("message should build");

        let raw = String::from_utf8(msg.formatted()).unwrap();
        assert!(raw.contains("Subject: Reset your password"));
        assert!(raw.contains("To: player@example.com"));
        assert!(raw.contains("From: BattleCrab <no-reply@battlecrab.com>"));
        assert!(raw.contains("multipart/alternative"));
        assert!(raw.contains("text/plain"));
        assert!(raw.contains("text/html"));
        // The token must survive MIME encoding intact or the link is useless.
        assert!(raw.replace("=\r\n", "").contains("token=abc"));
    }

    #[test]
    fn an_invalid_recipient_is_rejected_before_sending() {
        let from: Mailbox = "a@b.c".parse().unwrap();
        let err = build_message(from, "not-an-address", "s", "t", "h").unwrap_err();
        assert!(matches!(err, MailError::Address(_)));
    }

    #[test]
    fn a_disabled_mailer_reports_itself_as_disabled() {
        let mailer = Mailer::disabled();
        assert!(!mailer.is_enabled());
    }

    #[tokio::test]
    async fn a_disabled_mailer_succeeds_without_sending() {
        // Local development must not fail just because SMTP is unconfigured.
        let mailer = Mailer::disabled();
        assert!(mailer
            .send_email_verification("a@b.c", "alice", "https://x/t")
            .await
            .is_ok());
        assert!(mailer
            .send_password_reset("a@b.c", "alice", "https://x/t")
            .await
            .is_ok());
    }
}
