/**
 * One in-game item icon, drawn from the sprite atlas.
 *
 * `l2icons.png` + `l2icons.json` are generated by `l2r-tools icon-atlas` from
 * the game client's texture packages — one 32×32 cell per icon the item
 * datapack references, addressed by lowercased references like
 * `icon.weapon_arcana_mace_i00`, which is exactly what the items API sends.
 *
 * Both files are imported as *assets* (the JSON via `with { type: "file" }`),
 * so they get content-hashed URLs and immutable caching, and neither costs
 * anything until the first icon actually renders: the map is fetched lazily
 * through react-query, and the browser only pulls the sheet when a cell first
 * paints it. While the map is in flight — or for an icon it doesn't know —
 * the cell renders as an empty socket rather than shifting the layout.
 */
import { useQuery } from "@tanstack/react-query";

import atlasUrl from "../../assets/l2icons.webp";
import mapAsset from "../../assets/l2icons.json" with { type: "file" };
import { cx } from "./ui";

// `with { type: "file" }` makes the bundler emit the JSON as a hashed asset
// and hand back its URL — but tsc still types the import as the file's
// *contents* (it resolves the real JSON and ignores the attribute), so the
// runtime value needs re-asserting. Do not "fix" this by dropping the
// attribute: that would inline the whole map into the bundle.
const mapUrl = mapAsset as unknown as string;

type IconMap = {
  cell: number;
  columns: number;
  icons: Record<string, number>;
};

function useIconMap(): IconMap | undefined {
  const { data } = useQuery({
    queryKey: ["l2icons"],
    queryFn: async (): Promise<IconMap> => {
      const response = await fetch(mapUrl);
      if (!response.ok) throw new Error(`icon map: HTTP ${response.status}`);
      return response.json();
    },
    // The map is immutable — its URL changes when its content does.
    staleTime: Infinity,
    gcTime: Infinity,
  });
  return data;
}

export function ItemIcon({
  icon,
  className,
  bare = false,
}: {
  icon: string | null;
  className?: string;
  /** Sprite only, no socket chrome — for hosts that draw their own slot. */
  bare?: boolean;
}) {
  const map = useIconMap();
  const index = icon !== null ? map?.icons[icon] : undefined;

  return (
    <span
      aria-hidden
      className={cx(
        // size-8 is exactly the 32px the icons are authored at — no scaling,
        // no blur. The border keeps an empty socket visible.
        "block size-8 shrink-0",
        !bare && "rounded-md border border-(--surface-border) bg-black/30",
        className,
      )}
      style={
        index !== undefined && map
          ? {
              backgroundImage: `url(${atlasUrl})`,
              backgroundPosition: `-${(index % map.columns) * map.cell}px -${
                Math.floor(index / map.columns) * map.cell
              }px`,
            }
          : undefined
      }
    />
  );
}
