//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub rowid: i32,
    pub login: Option<String>,
    pub password: Option<String>,
    pub email: Option<String>,
    pub is_verified: Option<i32>,
    pub created_time: String,
    pub lastactive: i64,
    #[sea_orm(column_name = "accessLevel")]
    pub access_level: i32,
    #[sea_orm(column_name = "lastIP")]
    pub last_ip: Option<String>,
    #[sea_orm(column_name = "lastServer")]
    pub last_server: Option<i32>,
    #[sea_orm(column_name = "pcIp")]
    pub pc_ip: Option<String>,
    pub hop1: Option<String>,
    pub hop2: Option<String>,
    pub hop3: Option<String>,
    pub hop4: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
