//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "accounts_ipauth")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub login: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ip: String,
    pub r#type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
