//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "auction_bid")]
pub struct Model {
    pub id: i32,
    #[sea_orm(column_name = "auctionId", primary_key, auto_increment = false)]
    pub auction_id: i32,
    #[sea_orm(column_name = "bidderId", primary_key, auto_increment = false)]
    pub bidder_id: i32,
    #[sea_orm(column_name = "bidderName")]
    pub bidder_name: String,
    pub clan_name: String,
    #[sea_orm(column_name = "maxBid")]
    pub max_bid: i64,
    pub time_bid: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
