//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "bbs_favorites")]
pub struct Model {
    #[sea_orm(column_name = "favId", primary_key, auto_increment = true)]
    pub fav_id: i32,
    #[sea_orm(column_name = "playerId")]
    pub player_id: i32,
    #[sea_orm(column_name = "favTitle")]
    pub fav_title: String,
    #[sea_orm(column_name = "favBypass")]
    pub fav_bypass: String,
    #[sea_orm(column_name = "favAddDate")]
    pub fav_add_date: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
