//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "bot_reported_char_data")]
pub struct Model {
    #[sea_orm(column_name = "botId", primary_key, auto_increment = false)]
    pub bot_id: i32,
    #[sea_orm(column_name = "reporterId", primary_key, auto_increment = false)]
    pub reporter_id: i32,
    #[sea_orm(column_name = "reportDate")]
    pub report_date: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
