//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "buylists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub buylist_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_id: i32,
    pub count: i64,
    pub next_restock_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
