//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "castle_functions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub castle_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub r#type: i32,
    pub lvl: i32,
    pub lease: i32,
    pub rate: i64,
    #[sea_orm(column_name = "endTime")]
    pub end_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
