//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "castle_manor_production")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub castle_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub seed_id: i32,
    pub amount: i32,
    pub start_amount: i32,
    pub price: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub next_period: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
