//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "castle_doorupgrade")]
pub struct Model {
    #[sea_orm(column_name = "doorId", primary_key, auto_increment = false)]
    pub door_id: i32,
    pub ratio: i32,
    #[sea_orm(column_name = "castleId")]
    pub castle_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
