//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "castle")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub side: String,
    pub treasury: i64,
    #[sea_orm(column_name = "siegeDate")]
    pub siege_date: i64,
    #[sea_orm(column_name = "regTimeOver")]
    pub reg_time_over: String,
    #[sea_orm(column_name = "regTimeEnd")]
    pub reg_time_end: i64,
    #[sea_orm(column_name = "showNpcCrest")]
    pub show_npc_crest: String,
    #[sea_orm(column_name = "ticketBuyCount")]
    pub ticket_buy_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
