//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "castle_trapupgrade")]
pub struct Model {
    #[sea_orm(column_name = "castleId", primary_key, auto_increment = false)]
    pub castle_id: i32,
    #[sea_orm(column_name = "towerIndex", primary_key, auto_increment = false)]
    pub tower_index: i32,
    pub level: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
