//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_macroses")]
pub struct Model {
    #[sea_orm(column_name = "charId", primary_key, auto_increment = false)]
    pub char_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub icon: Option<i32>,
    pub name: Option<String>,
    pub descr: Option<String>,
    pub acronym: Option<String>,
    pub commands: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
