//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_summons")]
pub struct Model {
    #[sea_orm(column_name = "ownerId", primary_key, auto_increment = false)]
    pub owner_id: i32,
    #[sea_orm(column_name = "summonId", primary_key, auto_increment = false)]
    pub summon_id: i32,
    #[sea_orm(column_name = "summonSkillId", primary_key, auto_increment = false)]
    pub summon_skill_id: i32,
    #[sea_orm(column_name = "curHp")]
    pub cur_hp: Option<i32>,
    #[sea_orm(column_name = "curMp")]
    pub cur_mp: Option<i32>,
    pub time: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
