//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_item_reuse_save")]
pub struct Model {
    #[sea_orm(column_name = "charId", primary_key, auto_increment = false)]
    pub char_id: i32,
    #[sea_orm(column_name = "itemId", primary_key, auto_increment = false)]
    pub item_id: i32,
    #[sea_orm(column_name = "itemObjId", primary_key, auto_increment = false)]
    pub item_obj_id: i32,
    #[sea_orm(column_name = "reuseDelay")]
    pub reuse_delay: i32,
    pub systime: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
