//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_premium_items")]
pub struct Model {
    #[sea_orm(column_name = "charId", primary_key, auto_increment = false)]
    pub char_id: i32,
    #[sea_orm(column_name = "itemNum", primary_key, auto_increment = false)]
    pub item_num: i32,
    #[sea_orm(column_name = "itemId")]
    pub item_id: i32,
    #[sea_orm(column_name = "itemCount")]
    pub item_count: i64,
    #[sea_orm(column_name = "itemSender")]
    pub item_sender: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
