//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_shortcuts")]
pub struct Model {
    #[sea_orm(column_name = "charId", primary_key, auto_increment = false)]
    pub char_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub slot: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub page: i32,
    pub r#type: Option<i32>,
    pub shortcut_id: Option<i64>,
    pub level: Option<i32>,
    pub sub_level: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub class_index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
