//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_summon_skills_save")]
pub struct Model {
    #[sea_orm(column_name = "ownerId", primary_key, auto_increment = false)]
    pub owner_id: i32,
    #[sea_orm(column_name = "ownerClassIndex", primary_key, auto_increment = false)]
    pub owner_class_index: i32,
    #[sea_orm(column_name = "summonSkillId", primary_key, auto_increment = false)]
    pub summon_skill_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub skill_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub skill_level: i32,
    pub skill_sub_level: i32,
    pub remaining_time: i32,
    pub buff_index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
