//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_contacts")]
pub struct Model {
    #[sea_orm(column_name = "charId", primary_key, auto_increment = false)]
    pub char_id: i32,
    #[sea_orm(column_name = "contactId", primary_key, auto_increment = false)]
    pub contact_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
