//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "characters")]
pub struct Model {
    pub account_name: Option<String>,
    #[sea_orm(column_name = "charId", primary_key, auto_increment = false)]
    pub char_id: i32,
    pub char_name: String,
    pub level: Option<i32>,
    #[sea_orm(column_name = "maxHp")]
    pub max_hp: Option<i32>,
    #[sea_orm(column_name = "curHp")]
    pub cur_hp: Option<f64>,
    #[sea_orm(column_name = "maxCp")]
    pub max_cp: Option<i32>,
    #[sea_orm(column_name = "curCp")]
    pub cur_cp: Option<f64>,
    #[sea_orm(column_name = "maxMp")]
    pub max_mp: Option<i32>,
    #[sea_orm(column_name = "curMp")]
    pub cur_mp: Option<f64>,
    pub face: Option<i32>,
    #[sea_orm(column_name = "hairStyle")]
    pub hair_style: Option<i32>,
    #[sea_orm(column_name = "hairColor")]
    pub hair_color: Option<i32>,
    pub sex: Option<i32>,
    pub heading: Option<i32>,
    pub x: Option<i32>,
    pub y: Option<i32>,
    pub z: Option<i32>,
    pub exp: Option<i64>,
    #[sea_orm(column_name = "expBeforeDeath")]
    pub exp_before_death: Option<i64>,
    pub sp: i64,
    pub reputation: Option<i32>,
    pub fame: i32,
    #[sea_orm(column_name = "raidbossPoints")]
    pub raidboss_points: i32,
    pub pvpkills: Option<i32>,
    pub pkkills: Option<i32>,
    pub clanid: Option<i32>,
    pub race: Option<i32>,
    pub classid: Option<i32>,
    pub base_class: i32,
    pub transform_id: i32,
    pub deletetime: i64,
    pub cancraft: Option<i32>,
    pub title: Option<String>,
    pub title_color: i32,
    pub accesslevel: Option<i32>,
    pub online: Option<i32>,
    pub onlinetime: Option<i32>,
    pub char_slot: Option<i32>,
    #[sea_orm(column_name = "lastAccess")]
    pub last_access: i64,
    pub clan_privs: Option<i32>,
    pub wantspeace: Option<i32>,
    pub power_grade: Option<i32>,
    pub nobless: i32,
    pub subpledge: i32,
    pub lvl_joined_academy: i32,
    pub apprentice: i32,
    pub sponsor: i32,
    pub clan_join_expiry_time: i64,
    pub clan_create_expiry_time: i64,
    pub bookmarkslot: i32,
    pub vitality_points: i32,
    #[sea_orm(column_name = "createDate")]
    pub create_date: String,
    pub language: Option<String>,
    pub faction: i32,
    pub pccafe_points: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
