//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "clan_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub clan_id: i32,
    pub clan_name: Option<String>,
    pub clan_level: Option<i32>,
    pub reputation_score: i32,
    #[sea_orm(column_name = "hasCastle")]
    pub has_castle: Option<i32>,
    pub blood_alliance_count: i32,
    pub blood_oath_count: i32,
    pub ally_id: Option<i32>,
    pub ally_name: Option<String>,
    pub leader_id: Option<i32>,
    pub crest_id: Option<i32>,
    pub crest_large_id: Option<i32>,
    pub ally_crest_id: Option<i32>,
    pub auction_bid_at: i32,
    pub ally_penalty_expiry_time: i64,
    pub ally_penalty_type: i32,
    pub char_penalty_expiry_time: i64,
    pub dissolving_expiry_time: i64,
    pub new_leader_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
