//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "clan_wars")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub clan1: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub clan2: String,
    #[sea_orm(column_name = "clan1Kill")]
    pub clan1_kill: i32,
    #[sea_orm(column_name = "clan2Kill")]
    pub clan2_kill: i32,
    #[sea_orm(column_name = "winnerClan")]
    pub winner_clan: String,
    #[sea_orm(column_name = "startTime")]
    pub start_time: i64,
    #[sea_orm(column_name = "endTime")]
    pub end_time: i64,
    pub state: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
