//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "clan_privs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub clan_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub rank: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub party: i32,
    pub privs: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
