//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "clanhall_auctions_bidders")]
pub struct Model {
    #[sea_orm(column_name = "clanHallId", primary_key, auto_increment = false)]
    pub clan_hall_id: i32,
    #[sea_orm(column_name = "clanId", primary_key, auto_increment = false)]
    pub clan_id: i32,
    pub bid: i64,
    #[sea_orm(column_name = "bidTime")]
    pub bid_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
