//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "commission_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub commission_id: i32,
    pub item_object_id: i32,
    pub price_per_unit: i64,
    pub start_time: String,
    pub duration_in_days: i32,
    pub discount_in_percentage: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
