//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "crests")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub crest_id: i32,
    #[sea_orm(column_type = "Binary(2176)")]
    pub data: Vec<u8>,
    pub r#type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
