//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "cursed_weapons")]
pub struct Model {
    #[sea_orm(column_name = "itemId", primary_key, auto_increment = false)]
    pub item_id: i32,
    #[sea_orm(column_name = "charId")]
    pub char_id: i32,
    #[sea_orm(column_name = "playerReputation")]
    pub player_reputation: Option<i32>,
    #[sea_orm(column_name = "playerPkKills")]
    pub player_pk_kills: Option<i32>,
    #[sea_orm(column_name = "nbKills")]
    pub nb_kills: Option<i32>,
    #[sea_orm(column_name = "endTime")]
    pub end_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
