//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "custom_mail")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub receiver: i32,
    pub subject: String,
    pub message: String,
    pub items: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
