//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "custom_teleport")]
pub struct Model {
    #[sea_orm(column_name = "Description")]
    pub description: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub loc_x: Option<i32>,
    pub loc_y: Option<i32>,
    pub loc_z: Option<i32>,
    pub price: Option<i32>,
    pub fornoble: i32,
    #[sea_orm(column_name = "itemId")]
    pub item_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
