//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fort_siege_guards")]
pub struct Model {
    #[sea_orm(column_name = "fortId")]
    pub fort_id: i32,
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i32,
    #[sea_orm(column_name = "npcId")]
    pub npc_id: i32,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub heading: i32,
    #[sea_orm(column_name = "respawnDelay")]
    pub respawn_delay: i32,
    #[sea_orm(column_name = "isHired")]
    pub is_hired: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
