//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fort_doorupgrade")]
pub struct Model {
    #[sea_orm(column_name = "doorId", primary_key, auto_increment = false)]
    pub door_id: i32,
    #[sea_orm(column_name = "fortId")]
    pub fort_id: i32,
    pub hp: i32,
    #[sea_orm(column_name = "pDef")]
    pub p_def: i32,
    #[sea_orm(column_name = "mDef")]
    pub m_def: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
