//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fort")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_name = "siegeDate")]
    pub siege_date: i64,
    #[sea_orm(column_name = "lastOwnedTime")]
    pub last_owned_time: i64,
    pub owner: i32,
    #[sea_orm(column_name = "fortType")]
    pub fort_type: i32,
    pub state: i32,
    #[sea_orm(column_name = "castleId")]
    pub castle_id: i32,
    #[sea_orm(column_name = "supplyLvL")]
    pub supply_lv_l: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
