//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "forums")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub forum_id: i32,
    pub forum_name: String,
    pub forum_parent: i32,
    pub forum_post: i32,
    pub forum_type: i32,
    pub forum_perm: i32,
    pub forum_owner_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
