//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "grandboss_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub boss_id: i32,
    pub loc_x: i32,
    pub loc_y: i32,
    pub loc_z: i32,
    pub heading: i32,
    pub respawn_time: i64,
    #[sea_orm(column_name = "currentHP")]
    pub current_hp: f64,
    #[sea_orm(column_name = "currentMP")]
    pub current_mp: f64,
    pub status: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
