//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "item_auction")]
pub struct Model {
    #[sea_orm(column_name = "auctionId", primary_key, auto_increment = false)]
    pub auction_id: i32,
    #[sea_orm(column_name = "instanceId")]
    pub instance_id: i32,
    #[sea_orm(column_name = "auctionItemId")]
    pub auction_item_id: i32,
    #[sea_orm(column_name = "startingTime")]
    pub starting_time: i64,
    #[sea_orm(column_name = "endingTime")]
    pub ending_time: i64,
    #[sea_orm(column_name = "auctionStateId")]
    pub auction_state_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
