//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "itemsonground")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub object_id: i32,
    pub item_id: Option<i32>,
    pub count: i64,
    pub enchant_level: Option<i32>,
    pub x: Option<i32>,
    pub y: Option<i32>,
    pub z: Option<i32>,
    pub drop_time: i64,
    pub equipable: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
