//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "item_auction_bid")]
pub struct Model {
    #[sea_orm(column_name = "auctionId", primary_key, auto_increment = false)]
    pub auction_id: i32,
    #[sea_orm(column_name = "playerObjId", primary_key, auto_increment = false)]
    pub player_obj_id: i32,
    #[sea_orm(column_name = "playerBid")]
    pub player_bid: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
