//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "items")]
pub struct Model {
    pub owner_id: Option<i32>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub object_id: i32,
    pub item_id: Option<i32>,
    pub count: i64,
    pub enchant_level: Option<i32>,
    pub loc: Option<String>,
    pub loc_data: Option<i32>,
    pub time_of_use: Option<i32>,
    pub custom_type1: Option<i32>,
    pub custom_type2: Option<i32>,
    pub mana_left: i32,
    pub time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
