//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "item_elementals")]
pub struct Model {
    #[sea_orm(column_name = "itemId", primary_key, auto_increment = false)]
    pub item_id: i32,
    #[sea_orm(column_name = "elemType", primary_key, auto_increment = false)]
    pub elem_type: i32,
    #[sea_orm(column_name = "elemValue")]
    pub elem_value: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
