//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "mdt_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub race_id: i32,
    pub first: Option<i32>,
    pub second: Option<i32>,
    pub odd_rate: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
