//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "merchant_lease")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub merchant_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub player_id: i32,
    pub bid: Option<i32>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub r#type: i32,
    pub player_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
