//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(column_name = "messageId", primary_key, auto_increment = false)]
    pub message_id: i32,
    #[sea_orm(column_name = "senderId")]
    pub sender_id: i32,
    #[sea_orm(column_name = "receiverId")]
    pub receiver_id: i32,
    pub subject: Option<String>,
    pub content: Option<String>,
    pub expiration: i64,
    #[sea_orm(column_name = "reqAdena")]
    pub req_adena: i64,
    #[sea_orm(column_name = "hasAttachments")]
    pub has_attachments: String,
    #[sea_orm(column_name = "isUnread")]
    pub is_unread: String,
    #[sea_orm(column_name = "isDeletedBySender")]
    pub is_deleted_by_sender: String,
    #[sea_orm(column_name = "isDeletedByReceiver")]
    pub is_deleted_by_receiver: String,
    #[sea_orm(column_name = "isLocked")]
    pub is_locked: String,
    #[sea_orm(column_name = "sendBySystem")]
    pub send_by_system: i32,
    #[sea_orm(column_name = "isReturned")]
    pub is_returned: String,
    #[sea_orm(column_name = "itemId")]
    pub item_id: i32,
    #[sea_orm(column_name = "enchantLvl")]
    pub enchant_lvl: i32,
    pub elementals: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
