//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "npc_respawns")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub heading: i32,
    #[sea_orm(column_name = "respawnTime")]
    pub respawn_time: i64,
    #[sea_orm(column_name = "currentHp")]
    pub current_hp: f64,
    #[sea_orm(column_name = "currentMp")]
    pub current_mp: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
