//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "olympiad_fights")]
pub struct Model {
    #[sea_orm(column_name = "charOneId", primary_key, auto_increment = false)]
    pub char_one_id: i32,
    #[sea_orm(column_name = "charTwoId", primary_key, auto_increment = false)]
    pub char_two_id: i32,
    #[sea_orm(column_name = "charOneClass")]
    pub char_one_class: i32,
    #[sea_orm(column_name = "charTwoClass")]
    pub char_two_class: i32,
    pub winner: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub start: i64,
    pub time: i64,
    pub classed: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
