//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "petition_feedback")]
pub struct Model {
    #[sea_orm(column_name = "charName", primary_key, auto_increment = false)]
    pub char_name: String,
    #[sea_orm(column_name = "gmName", primary_key, auto_increment = false)]
    pub gm_name: String,
    pub rate: i32,
    pub message: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
