//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "pets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_obj_id: i32,
    pub name: Option<String>,
    pub level: i32,
    #[sea_orm(column_name = "curHp")]
    pub cur_hp: Option<f64>,
    #[sea_orm(column_name = "curMp")]
    pub cur_mp: Option<f64>,
    pub exp: Option<i64>,
    pub sp: Option<i64>,
    pub fed: Option<i32>,
    #[sea_orm(column_name = "ownerId")]
    pub owner_id: i32,
    pub restore: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
