//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "pledge_recruit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub clan_id: i32,
    pub karma: i32,
    pub information: String,
    pub detailed_information: String,
    pub application_type: i32,
    pub recruit_type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
