//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "posts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub post_id: i32,
    pub post_owner_name: String,
    pub post_ownerid: i32,
    pub post_date: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub post_topic_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub post_forum_id: i32,
    pub post_txt: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
