//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "siege_clans")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub castle_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub clan_id: i32,
    pub r#type: Option<i32>,
    pub castle_owner: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
