//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "topic")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub topic_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub topic_forum_id: i32,
    pub topic_name: String,
    pub topic_date: i64,
    pub topic_ownername: String,
    pub topic_ownerid: i32,
    pub topic_type: i32,
    pub topic_reply: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
