#!/usr/bin/env python3
"""Generate the typed system-message table in `commons` from the Java reference.

The client decides what a system message *says* and what colour it appears in;
the server only ever sends an id and its parameters. So three sources are
merged here:

* `SystemMessageId.java` in the Java reference — the canonical name, id and
  English text of every retail message (`@ClientString(id, message)`).
* the client's own `SystemMsg*.dat` — the colour each id is drawn in, which
  Java does not record.
* `tools/custom_system_messages.json` — messages this server adds.

Arity comes from the *name*, exactly as Java's `parseMessageParameters` does:
the highest `C<n>`/`S<n>` token wins. `C` is a name (player or npc), `S` is
anything else — an int, an item, a skill. Which of those a caller passes is
their choice, so only the count is enforced, never the type.

Only messages that take parameters become types; the 4120 that take none are
plain constants, which keeps the generated file about a quarter the size it
would otherwise be.

The output is committed. This script exists so it can be re-run against a newer
client or Java drop and the diff reviewed.

Usage:
    python3 tools/gen_system_messages.py \\
        ../interlude_classic/java/org/l2jmobius/gameserver/network/SystemMessageId.java \\
        dist/client/system_decrypted/SystemMsg_Classic-eu.dat \\
        crates/commons/src/system_messages/generated.rs
"""

import json
import pathlib
import re
import sys

CUSTOM = pathlib.Path(__file__).with_name("custom_system_messages.json")

ANNOTATION = re.compile(
    r'@ClientString\(id = (-?\d+), message = "((?:[^"\\]|\\.)*)"\)\s*\n'
    r"\s*public static SystemMessageId (\w+);"
)


def arity(name):
    """Highest C<n>/S<n> in the name — Java's `parseMessageParameters`."""
    count = 0
    for i in range(len(name) - 1):
        if name[i] in "CS" and name[i + 1].isdigit():
            count = max(count, int(name[i + 1]))
    return count


def slots(name, n):
    """Which parameter positions are names (`C`) and which are values (`S`).

    A name mentions its tokens in sentence order, not parameter order, so this
    maps position -> kind rather than trusting the order they appear in.
    """
    kind = {}
    for i in range(len(name) - 1):
        if name[i] in "CS" and name[i + 1].isdigit():
            kind[int(name[i + 1])] = name[i]
    # A gap means the name skips an index (e.g. C1 and S3 with no 2). Treat any
    # unnamed position as a value; the client still expects it to be sent.
    return [kind.get(i, "S") for i in range(1, n + 1)]


def parse_java(path):
    text = pathlib.Path(path).read_text(encoding="utf-8", errors="replace")
    out = []
    for raw_id, message, name in ANNOTATION.findall(text):
        out.append(
            {
                "id": int(raw_id),
                "name": name,
                "message": message.replace('\\"', '"'),
                "color": None,
                "custom": False,
            }
        )
    return out


def parse_dat_colors(path):
    """id -> RRGGBBAA, read from the unpacked text form of the client table."""
    colors = {}
    for line in pathlib.Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
        fields = line.split("\t")
        if len(fields) > 5 and fields[0] == "msg_begin":
            try:
                colors[int(fields[1])] = fields[5].upper()
            except ValueError:
                pass
    return colors


def rust_string(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


HEADER = '''//! Every system message the client knows, as ids and typed constructors.
//!
//! GENERATED by `tools/gen_system_messages.py` — do not hand-edit. Add server
//! messages to `tools/custom_system_messages.json` and re-run it.
//!
//! The server sends an id and its parameters; the client supplies the wording
//! and the colour from its own `SystemMsg*.dat`. The text and colour recorded
//! here therefore exist to *generate* that file (`l2r-tools client-dat
//! sync-messages`), not to be sent — changing a string here changes nothing
//! until the client table is rebuilt.
//!
//! Messages that take parameters are types, so the count cannot be got wrong:
//!
//! ```ignore
//! C1_HAS_INFLICTED_S3_DAMAGE_ON_C2::new(attacker, victim, damage)
//! ```
//!
//! Arguments are in *parameter* order — the order the packet carries them —
//! which is not the order the tokens appear in the name. Messages that take
//! none are plain constants:
//!
//! ```ignore
//! YOU_CANNOT_MOVE_WHILE_SITTING
//! ```
//!
//! `C` positions take a [`Subject`] (a player or npc name) and `S` positions a
//! [`SmValue`]. Which kind of value an `S` carries is the caller\'s choice —
//! the client renders whatever type byte it is sent — so only the count is
//! enforced here.

// `new` deliberately returns a ready-to-send `SystemMessage` rather than the
// marker type it is called on: the type exists only to name the message and
// fix its arity, so returning `Self` would give the caller nothing.
#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    clippy::too_many_arguments,
    clippy::new_ret_no_self,
    clippy::new_without_default
)]

use super::{MessageInfo, SmValue, Subject, SystemMessage, SystemMessageId};

'''


def main(argv):
    java_path, dat_path, out_path = argv[1], argv[2], argv[3]

    entries = parse_java(java_path)
    colors = parse_dat_colors(dat_path)
    for entry in entries:
        entry["color"] = colors.get(entry["id"], "FFFFFFFF")

    custom = json.loads(CUSTOM.read_text())["messages"]
    known = {e["id"] for e in entries}
    for c in custom:
        if c["id"] in known:
            sys.exit(f"custom message id {c['id']} collides with a retail one")
        entries.append(
            {
                "id": c["id"],
                "name": c["name"],
                "message": c["message"],
                "color": c["color"].upper(),
                "custom": True,
            }
        )

    # A name can appear twice in the Java file; keep the first and drop later
    # duplicates so the generated module has unique items.
    seen = set()
    unique = []
    for entry in sorted(entries, key=lambda e: e["id"]):
        if entry["name"] in seen:
            continue
        seen.add(entry["name"])
        unique.append(entry)

    parts = [HEADER]
    with_params = [e for e in unique if arity(e["name"]) > 0]
    without = [e for e in unique if arity(e["name"]) == 0]

    parts.append(
        f"/// Messages that take no parameters ({len(without)} of them).\n"
        "///\n"
        "/// Each is a [`SystemMessageId`]; `.into()` turns one into a\n"
        "/// [`SystemMessage`] ready to send.\n"
    )
    for e in without:
        parts.append(f'/// `{rust_string(e["message"])}`\n')
        parts.append(
            f'pub const {e["name"]}: SystemMessageId = SystemMessageId::new({e["id"]});\n'
        )
    parts.append("\n")

    parts.append(f"// --- {len(with_params)} messages that take parameters ---\n\n")
    for e in with_params:
        n = arity(e["name"])
        kinds = slots(e["name"], n)
        args = []
        pushes = []
        for i, kind in enumerate(kinds, start=1):
            ty = "Subject" if kind == "C" else "SmValue"
            args.append(f"{kind.lower()}{i}: impl Into<{ty}>")
            pushes.append(f"{kind.lower()}{i}.into().into_param()")
        parts.append(f'/// `{rust_string(e["message"])}`\n')
        parts.append(f'pub struct {e["name"]};\n')
        parts.append(f"impl {e['name']} {{\n")
        parts.append(f"    pub const ID: i32 = {e['id']};\n\n")
        parts.append(f"    pub fn new({', '.join(args)}) -> SystemMessage {{\n")
        parts.append(f"        SystemMessage::new({e['id']}, vec![\n")
        for push in pushes:
            parts.append(f"            {push},\n")
        parts.append("        ])\n    }\n}\n\n")

    # The table the dat exporter reads.
    parts.append(
        "/// Every message, for rebuilding the client table.\n"
        "///\n"
        "/// `custom` marks the ones this server adds: `sync-messages` appends\n"
        "/// those to the dat with defaults for the columns it cannot know,\n"
        "/// because an id the client has no row for renders as nothing.\n"
        "pub static ALL: &[MessageInfo] = &[\n"
    )
    for e in unique:
        parts.append(
            f'    MessageInfo {{ id: {e["id"]}, name: "{e["name"]}", '
            f'text: "{rust_string(e["message"])}", color: "{e["color"]}", '
            f'params: {arity(e["name"])}, custom: {str(e["custom"]).lower()} }},\n'
        )
    parts.append("];\n")

    pathlib.Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    pathlib.Path(out_path).write_text("".join(parts))
    print(
        f"{len(unique)} messages -> {out_path} "
        f"({len(with_params)} typed, {len(without)} constants, "
        f"{sum(1 for e in unique if e['custom'])} custom)"
    )


if __name__ == "__main__":
    main(sys.argv)
